// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/file-stream.ts";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/products/index.tsx";
import * as $$0 from "./islands/ProductCard.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/file-stream.ts": $2,
    "./routes/index.tsx": $3,
    "./routes/products/index.tsx": $4,
  },
  islands: {
    "./islands/ProductCard.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
